# Generated by Django 5.0.2 on 2024-03-03 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('format', models.CharField(max_length=10)),
                ('genre', models.CharField(choices=[('genre_1', '1'), ('genre_2', '2'), ('genre_3', '3')], max_length=50)),
                ('picture', models.ImageField(upload_to='pictures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
    ]
