# Generated by Django 5.0.3 on 2024-03-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picturemodel',
            old_name='picture',
            new_name='image',
        ),
    ]
